## Task5
Created custom exceptions TrackNotFoundException, TrackAlreadyExistsException in a
com.stackroute.exceptions package.